### ISSUE TITLE
All user-id's in the API should be renamed and re-referenced to Identity Id

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#142]
**Describe the bug**
Previously we used User ID to retrieve the user, this was fine when we did not have an identity server. Now that we have an identity server, we need to start using identity Id instead of user id to retrieve users, update users, delete users. 
This is not only a problem in the user endpoint, but also a problem in resources like the ProjectResource.

**Expected behavior**
Rename all user id references to identity id, including the documentation, resources and endpoints.

**Comment by Brend-Smits** [comment]
I think when returning the user when creating projects, it might be best to also return the identity id instead of the user id. If the user id is only used internally and should not be used in the API, I don't think there's a benefit to showing it when creating a project for example.

This is what currently is returned when creating a project:
`{
    "id": 46,
    "user": {
        "id": 35,
        "name": "Developer",
        "email": "Developer@DEX.com",
        "identityId": "818727",
        "profileUrl": null,
        "role": null
    },
    "userId": 35,
    "name": "postmantest_projectname_updated",
    "description": "postmantest_description",
    "shortDescription": "postmantest_shortdesc",
    "uri": "postmantest_uri",
    "collaborators": [
        {
            "id": 9973,
            "fullName": "postmantest_collfullname",
            "role": "postmantest_collrole"
        }
    ],
    "created": "2020-04-20T08:24:26.693Z",
    "updated": "2020-04-20T08:24:26.693Z"
}`

**Comment by StijnGroenen** [comment]
Is the Identity ID generated by our IdentityServer or is it provided by the external identity provider (SURFconext)? If it is provided by the external identity provider, it should not be used by Digital Excellence as the primary ID since we have no control over it and we can not guarantee that it will be unique.

**Comment by wotwot563** [comment]
I had a discussion with @StijnGroenen  and we both agreed that it would not be good to have the identity id as a user id. mainly because we cannot guarantee that the studentid is unique.

The best way in our opinion would be to match the source and an unique id(be it student id or provider id) to one user and extract the user id from that.
This will need some testing when we actually have SURFConext implemented because we dont know the exact properties a SURFConext token has.
