### ISSUE TITLE
Setup a Notification System

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#230]
**Is your feature request related to a problem? Please describe.**
There is no way to interact with the community with notifications or emails. 

**Describe the solution you'd like**
We want a notification system in which we can let a user know when the content they follow (like users, tags/categories/projects) update. We will use the email system to provide daily/weekly/monthly updates to users based on their interests. An example is how Github does it based on your personal preferences: gyazo.com/d35ef4318f1cd2e7d4ccb52572ec0c7c

We need to find out and design an efficient system for these kinds of notifications. 

**Additional context**
This is a large issue and possibly multiple backend users should work together on designing and implementing this system. We should also be aware to not reinvent the wheel and look at how other applications do this.
For emails I would like to take a look at using an email delivery service such as SendGrid. However, I need to see if we can retrieve an open-source license for this.  (edit: looks like they don't offer an open source license but instead have free products which will be fine for our use cases: https://sendgrid.com/pricing/)
Comments and Suggestions are welcome.

**Comment by Maxvanhattum** [comment]
This could re-use the recommendation system I saw pass by earlier. Then add some extra logic to only recommend projects from the previous week and maybe allow room for "sponsored" recommended projects that everyone gets. 
Could just set it up as logic in the back-end with a dedicated endpoint and configure a cronjob to call this weekly. 
Sounds like a fun issue that I want to be involved in.

**Comment by Maxvanhattum** [comment]
I did a bit more research in to this. I suggest just making a stand-alone notification handler, which can recieve contents and the notification type, handling the data and passing it along to another class that handles the method of sending. 
If designed correctly it would easily allow other systems to utilize the notification system. 
Moreover this way we could not only use it for sending emails, but maybe at a later point of time also for realtime notifications with websockets or for push notifications. 

For specific technologies, the best options in my opinion are to make it a REST API so that it can be approached from the web, or make it a service to make it more contained. As for the messaging by email right now, i looked into sendgrid and they allow easy dynamic templating, see: https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/#design-a-dynamic-transactional-template and https://github.com/sendgrid/email-templates/tree/master/dynamic-templates . 

This resource looks really extensive touching on how the architecture of such a service could look like: https://medium.com/swlh/architecting-a-scalable-notification-service-778c6fb3ac28 . It's focussed on webshop notifications based on products etc but a lot of the core concepts can be used. 
From what I (vaguely) remember of design patterns and from research done I think we could utilize the observer pattern in our design, see: https://stackabuse.com/the-observer-design-pattern-in-java/ which uses notifications as a means to explain this pattern. 
When searching online for existing implementations most try to indeed separate the data handler and the sending methods for obvious reasons, some examples: https://www.codeproject.com/Articles/42843/Email-Notification-Framework, https://www.ipointsystems.com/blog/2018/july/sending-mails-with-c . 

I'd like input as to what you all prefer or if there are better ways that I missed. My preference is as summarized: a seperate handler which can recieve dynamic data and registers notifications based on the observer pattern, when fired passing it along to one of the available actual notification methods available. 
@Brend-Smits let me know what you think, if you want me to I can put this research in a separate, more official document. If no one else has better suggestions I can go ahead and move on to a first draft of actual software designs.
