### ISSUE TITLE
ProjectLike Infinite Project References

### ISSUE THREAD

**Issue by Maxvanhattum** [DigitalExcellence/dex-backend#341]
**Describe the bug**
In the Models _Project_ class, a list of _ProjectLike_ is present. However in _ProjectLike_ there is again a reference to the aforementioned _Project_, essentially creating an infinite chain. Moreover in _ProjectLike_ there is redundant information in the properties, a 'CreatorOfProject' _User_ property is present, while this is already in the parent _Project_ entity. 
Also the user that actually made the like is only referenced by an Integer property 'UserId', this should probably also have the whole _User_ Entity as a property. 

**To Reproduce**
1. Open the solution.
2. Go to class library 5_models
3. Open Project.cs
4. Open ProjectLike.cs

**Expected behavior**
Code should be DRY and follow SOLID principles.

**Comment by Yuqera** [comment]
I would like to add that this is also the case with the User class. When the user likes his own project the ProjectLike class will reference the CreatorOfProject which contains a list of ProjectLikes referencing back to the ProjectLike with the user.

**Comment by Yuqera** [comment]
I will be refactoring the ProjectLike class to: 
`class ProjectLike {
  public int Id { get; set; }
  public int ProjectId { get; set; }
  public int UserThatLikedId { get; set; }
  public DateTime Date { get; set; }
}` so there won't be any references.

**Comment by Yuqera** [comment]
Okay, I've finnaly come to the conclusion that this isn't a bug that needs to be fixed. 
The objects referencing itself is part of the database design to create a Many to Many relationship. The other method would be to do something along the lines of this:
`class Object1 
{
  public int Id { get; set; }
  public Object2 Object2 { get; set; } 
}

class Object2
{
  public int Id { get; set; }
  public Object1 Object1 { get; set; } 
}

class Object1Object2 
{
  public int Object1Id { get; set; }
  public int Object2Id { get; set; }
}`

That being said, why isn't this a bug? There's 2 reasons:
 - First of all, the expected behaviour is that it should follow SOLID and DRY principles, but this issue doesn't come up in the SOLID and DRY issues. Nowhere in SOLID states that objectA inside an objectB inside objectA is any issue.  DRY means "Don't Repeat Yourself", even though the word "Repeat" sounds like it fits in this case, it does not. The actual principle of DRY does not apply here, so doesn't SOLID.
  - Secondly, the problem would be that the program would crash because it's referencing itself infinitely. Except luckily there's Lazy Loading in C#. More on that you can find at "[https://thinkdotnet.wordpress.com/2017/10/26/lazy-loading/](url)" under the section "Varieties->Ghost".

**Comment by niraymak** [comment]
Reopened this issue because naming is not right. CreatorOfProject attribute is actually the one who likes the project.

**Comment by Maxvanhattum** [comment]
> Okay, I've finnaly come to the conclusion that this isn't a bug that needs to be fixed.
> The objects referencing itself is part of the database design to create a Many to Many relationship. The other method would be to do something along the lines of this:
> 
Ah yes my bad, seems like entity framework uses bidirectional relationships as its standard when using this kind of code first approach. Good catch.
