### ISSUE TITLE
GitHub actions integration logs are hard to read

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#395]
**Is your feature request related to a problem? Please describe.**
In GitHub actions the integration tests log a lot of lines in the console which makes it hard to see the what went wrong.

**Describe the solution you'd like**
A lot of the logged lines are unneccessary. Maybe we can consider to only log the results in GitHub actions.

**Production URL**
https://github.com/DigitalExcellence/dex-backend/pull/391/checks?check_run_id=2031295751

**Additional context**
We currently use the Postman CLI runner called Newman.
https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/

**Comment by TomiEckert** [comment]
Newman uses [reporters](https://github.com/postmanlabs/newman#reporters) to output the results (file or console). There are some built in reporter options, which can work here:
- `--reporter-cli-no-console`: this removes the garbage and javascript stuff, only leaves the results
- `--reporter-cli-no-success-assertions`: this one removes the green ticks on successful requests

After these, reports go from ~45 to ~5 lines per test. This means an output of ~6.5k lines instead of 58k.

`--reporter-cli-no-banner`: can be helpful if the json collection will be split up into multiple smaller ones based on #364.

It's also possible to completely ignore the successful tests and only show the failed ones, but one needs to implement a [custom reporter](https://github.com/postmanlabs/newman#creating-your-own-reporter) for Newman.
