### ISSUE TITLE
Unclear Resource / ResourceResults

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-backend#413]
**Is your feature request related to a problem? Please describe.**
During our retrospective one of the points of attention was that we have many resources and resource results classes.

**Describe the solution you'd like**
Research how we can improve this. Maybe we can change naming conventions for resources and resource results to make it more clear. It also might be a good idea to investigate how this is handled in other projects.

**Production URL**
https://github.com/DigitalExcellence/dex-backend/tree/develop/API/Resources

**Additional context**

**Comment by RubenFricke** [comment]
In my opinion, I don't think the resources/resource results are really a problem, I think the problem is more with the fact that there are just too many in that one folder. Maybe adding subfolders would help and I think that the existing idea to migrate to microservice architecture would also help because it would split the resource results into different projects (contact @Maxvanhattum for information about the microservice ideas/plans).

**Comment by MeesvanStraten** [comment]
(For whoever that will work on this) For now I think it would be nice to atleast create a structured folder system. It's a quick fix and does not cost to much time.
