### ISSUE TITLE
Projects should have an embed button that generates an iframe

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-backend#56]
In GitLab by @Brend-Smits on Mar 29, 2020, 12:54

There needs to be an embed button that generates an iframe. This allows for Fontys or other websites to easily share projects and link them on their website on for example an Open Day.  
This also requires some more discussion with @wilrikdeloose , what should we do with non-public projects? Should they not be embeddable? Or only by users with a particular role?  
  
Related Epic: https://git.fhict.nl/dex/dex-epics/-/issues/2

**Comment by wotwot563** [comment]
I have looked into this issue and propose the following:

For public projects, anyone signed in could create a embed iframe.

For private projects, only the owner of that project or a person with more authority(teacher, admin) could generate a link with a GUID which gives permission to show that project in public. This means that the link can be disabled if the GUID is retracted.
For each individual user that requests an embed iframe there will be a new GUID so that individual embedded websites can be closed.


this way there is no need for authentication on the iframe page.

**Comment by Brend-Smits** [comment]
This is open for discussion, @wilrikdeloose and @DigitalExcellence/backend 
What do you all think? How should this be handled?

**Comment by StijnGroenen** [comment]
Since we have generalized the project structure (Issue #79), I think all projects are (and should be) publicly available (at least for now).

**Comment by Brend-Smits** [comment]
Yes, this definitely simplifies this issue. Right @wotwot563 ? 
Are there any other topics that need discussing regarding this issue or can implementation start?

**Comment by wotwot563** [comment]
there is already an implementation, the only addition it needs is user validation

**Comment by Brend-Smits** [comment]
> user validation

User validation? Are you saying that it's already implemented in some branch? 
Can you open a WIP PR please?

**Comment by wotwot563** [comment]
https://github.com/DigitalExcellence/dex-backend/pull/131
